main: me.MakePortals.main.Main
name: MakePortals
author: CJM
version: 1.1
api-version: 1.13
description: Creates portals to set locations
commands:
  MakePortals:
    aliases: [mp]
    usage: /<MakePortals> [args]
    description: Main Command